// Complete list of HealthKit types

export const QUANTITY_TYPES = [
  // Body Measurements
  "bodyMassIndex",
  "bodyFatPercentage",
  "height",
  "bodyMass",
  "leanBodyMass",
  "waistCircumference",
  // Fitness
  "stepCount",
  "distanceWalkingRunning",
  "distanceCycling",
  "distanceWheelchair",
  "distanceSwimming",
  "distanceDownhillSnowSports",
  "basalEnergyBurned",
  "activeEnergyBurned",
  "flightsClimbed",
  "appleExerciseTime",
  "appleMoveTime",
  "appleStandTime",
  "vo2Max",
  "walkingSpeed",
  "walkingDoubleSupportPercentage",
  "walkingAsymmetryPercentage",
  "walkingStepLength",
  "sixMinuteWalkTestDistance",
  "stairAscentSpeed",
  "stairDescentSpeed",
  "runningStrideLength",
  "runningVerticalOscillation",
  "runningGroundContactTime",
  "runningPower",
  "runningSpeed",
  "physicalEffort",
  // Vitals
  "heartRate",
  "bodyTemperature",
  "basalBodyTemperature",
  "bloodPressureSystolic",
  "bloodPressureDiastolic",
  "respiratoryRate",
  "restingHeartRate",
  "walkingHeartRateAverage",
  "heartRateVariabilitySDNN",
  "heartRateRecoveryOneMinute",
  "oxygenSaturation",
  "peripheralPerfusionIndex",
  // Results
  "bloodGlucose",
  "electrodermalActivity",
  "forcedExpiratoryVolume1",
  "forcedVitalCapacity",
  "inhalerUsage",
  "insulinDelivery",
  "numberOfTimesFallen",
  "peakExpiratoryFlowRate",
  "bloodAlcoholContent",
  // Nutrition
  "dietaryFatTotal",
  "dietaryFatPolyunsaturated",
  "dietaryFatMonounsaturated",
  "dietaryFatSaturated",
  "dietaryCholesterol",
  "dietarySodium",
  "dietaryCarbohydrates",
  "dietaryFiber",
  "dietarySugar",
  "dietaryEnergyConsumed",
  "dietaryProtein",
  "dietaryVitaminA",
  "dietaryVitaminB6",
  "dietaryVitaminB12",
  "dietaryVitaminC",
  "dietaryVitaminD",
  "dietaryVitaminE",
  "dietaryVitaminK",
  "dietaryCalcium",
  "dietaryIron",
  "dietaryThiamin",
  "dietaryRiboflavin",
  "dietaryNiacin",
  "dietaryFolate",
  "dietaryBiotin",
  "dietaryPantothenicAcid",
  "dietaryPhosphorus",
  "dietaryIodine",
  "dietaryMagnesium",
  "dietaryZinc",
  "dietarySelenium",
  "dietaryCopper",
  "dietaryManganese",
  "dietaryChromium",
  "dietaryMolybdenum",
  "dietaryChloride",
  "dietaryPotassium",
  "dietaryCaffeine",
  "dietaryWater",
  // Other
  "uvExposure",
  "environmentalAudioExposure",
  "headphoneAudioExposure",
  "numberOfAlcoholicBeverages",
  "atrialFibrillationBurden",
  "underwaterDepth",
  "waterTemperature",
  "appleSleepingWristTemperature",
  "timeInDaylight",
];

export const CATEGORY_TYPES = [
  // Sleep
  "sleepAnalysis",
  // Activity
  "appleStandHour",
  "lowCardioFitnessEvent",
  // Reproductive Health
  "menstrualFlow",
  "intermenstrualBleeding",
  "infrequentMenstrualCycles",
  "irregularMenstrualCycles",
  "persistentIntermenstrualBleeding",
  "prolongedMenstrualPeriods",
  "cervicalMucusQuality",
  "ovulationTestResult",
  "pregnancy",
  "pregnancyTestResult",
  "lactation",
  "contraceptive",
  "sexualActivity",
  // Mindfulness
  "mindfulSession",
  // Heart
  "highHeartRateEvent",
  "lowHeartRateEvent",
  "irregularHeartRhythmEvent",
  // Hearing
  "audioExposureEvent",
  "environmentalAudioExposureEvent",
  "headphoneAudioExposureEvent",
  // Other
  "toothbrushingEvent",
  "handwashingEvent",
  // Symptoms
  "abdominalCramps",
  "acne",
  "appetiteChanges",
  "bladderIncontinence",
  "bloating",
  "breastPain",
  "chestTightnessOrPain",
  "chills",
  "constipation",
  "coughing",
  "diarrhea",
  "dizziness",
  "drySkin",
  "fainting",
  "fatigue",
  "fever",
  "generalizedBodyAche",
  "hairLoss",
  "headache",
  "heartburn",
  "hotFlashes",
  "lossOfSmell",
  "lossOfTaste",
  "lowerBackPain",
  "memoryLapse",
  "moodChanges",
  "nausea",
  "nightSweats",
  "pelvicPain",
  "rapidPoundingOrFlutteringHeartbeat",
  "runnyNose",
  "shortnessOfBreath",
  "sinusCongestion",
  "skippedHeartbeat",
  "sleepChanges",
  "soreThroat",
  "vaginalDryness",
  "vomiting",
  "wheezing",
];

export const WORKOUT_TYPES = [
  "americanFootball",
  "archery",
  "australianFootball",
  "badminton",
  "barre",
  "baseball",
  "basketball",
  "bowling",
  "boxing",
  "cardioDance",
  "climbing",
  "cooldown",
  "coreTraining",
  "cricket",
  "crossCountrySkiing",
  "crossTraining",
  "curling",
  "cycling",
  "dance",
  "discSports",
  "downhillSkiing",
  "elliptical",
  "equestrianSports",
  "fencing",
  "fishing",
  "fitnessGaming",
  "flexibility",
  "functionalStrengthTraining",
  "golf",
  "gymnastics",
  "handCycling",
  "handball",
  "highIntensityIntervalTraining",
  "hiking",
  "hockey",
  "hunting",
  "jumpRope",
  "kickboxing",
  "lacrosse",
  "martialArts",
  "mindAndBody",
  "mixedCardio",
  "paddleSports",
  "pickleball",
  "pilates",
  "play",
  "preparationAndRecovery",
  "racquetball",
  "rowing",
  "rugby",
  "running",
  "sailing",
  "skatingSports",
  "snowboarding",
  "snowSports",
  "soccer",
  "socialDance",
  "softball",
  "squash",
  "stairClimbing",
  "stairs",
  "stepTraining",
  "surfingSports",
  "swimming",
  "tableTennis",
  "taiChi",
  "tennis",
  "trackAndField",
  "traditionalStrengthTraining",
  "transition",
  "volleyball",
  "walking",
  "waterFitness",
  "waterPolo",
  "waterSports",
  "wheelchairRunPace",
  "wheelchairWalkPace",
  "wrestling",
  "yoga",
  "other",
];

interface TypeInfo {
  category: string;
  unit?: string;
}

export const QUANTITY_TYPE_INFO: Record<string, TypeInfo> = {
  // Body Measurements
  bodyMassIndex: { category: "Body", unit: "count" },
  bodyFatPercentage: { category: "Body", unit: "%" },
  height: { category: "Body", unit: "m" },
  bodyMass: { category: "Body", unit: "kg" },
  leanBodyMass: { category: "Body", unit: "kg" },
  waistCircumference: { category: "Body", unit: "m" },
  // Fitness
  stepCount: { category: "Fitness", unit: "count" },
  distanceWalkingRunning: { category: "Fitness", unit: "m" },
  distanceCycling: { category: "Fitness", unit: "m" },
  distanceSwimming: { category: "Fitness", unit: "m" },
  basalEnergyBurned: { category: "Fitness", unit: "kcal" },
  activeEnergyBurned: { category: "Fitness", unit: "kcal" },
  flightsClimbed: { category: "Fitness", unit: "count" },
  appleExerciseTime: { category: "Fitness", unit: "min" },
  vo2Max: { category: "Fitness", unit: "mL/kg/min" },
  // Vitals
  heartRate: { category: "Vitals", unit: "count/min" },
  bodyTemperature: { category: "Vitals", unit: "degC" },
  bloodPressureSystolic: { category: "Vitals", unit: "mmHg" },
  bloodPressureDiastolic: { category: "Vitals", unit: "mmHg" },
  respiratoryRate: { category: "Vitals", unit: "count/min" },
  restingHeartRate: { category: "Vitals", unit: "count/min" },
  oxygenSaturation: { category: "Vitals", unit: "%" },
  // Nutrition
  dietaryEnergyConsumed: { category: "Nutrition", unit: "kcal" },
  dietaryProtein: { category: "Nutrition", unit: "g" },
  dietaryCarbohydrates: { category: "Nutrition", unit: "g" },
  dietaryFatTotal: { category: "Nutrition", unit: "g" },
  dietaryWater: { category: "Nutrition", unit: "mL" },
  dietaryCaffeine: { category: "Nutrition", unit: "mg" },
};

export const CATEGORY_TYPE_INFO: Record<string, TypeInfo> = {
  sleepAnalysis: { category: "Sleep" },
  appleStandHour: { category: "Activity" },
  mindfulSession: { category: "Mindfulness" },
  menstrualFlow: { category: "Reproductive" },
  highHeartRateEvent: { category: "Heart" },
  lowHeartRateEvent: { category: "Heart" },
  headache: { category: "Symptoms" },
  fatigue: { category: "Symptoms" },
  nausea: { category: "Symptoms" },
};
